dist: trusty
sudo: required
language: rust
rust:
 - stable
 - beta
 - nightly
cache:
directories:
- $HOME/.cargo

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_install:

  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.5.0/cassandra-cpp-driver-dbg_2.5.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.5.0/cassandra-cpp-driver-dev_2.5.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.5.0/cassandra-cpp-driver_2.5.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.8.0/libuv-dbg_1.8.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.8.0/libuv-dev_1.8.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.8.0/libuv_1.8.0-1_amd64.deb
  - sudo dpkg -i libuv-dbg_1.8.0-1_amd64.deb libuv-dev_1.8.0-1_amd64.deb libuv_1.8.0-1_amd64.deb cassandra-cpp-driver_2.5.0-1_amd64.deb cassandra-cpp-driver-dbg_2.5.0-1_amd64.deb cassandra-cpp-driver-dev_2.5.0-1_amd64.deb

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
script:
- |
  cargo build &&
  cargo test
after_success:
- travis-cargo coveralls --no-sudo
